### ISSUE TITLE
FATA[0000] no binary release of go1.12 for darwin/arm64 at https://dl.google.com/go/go1.12.darwin-arm64.tar.gz

### ISSUE THREAD

**Issue by xcrossed** [koron/goup#3]
```
goup version     
```
goup version v0.5.2

```
goup install 1.12 
```

Error: no binary release of go1.12 for darwin/arm64 at https://dl.google.com/go/go1.12.darwin-arm64.tar.gz
Usage:
  goup install [VERSION] [flags]

Examples:

  goup install
  goup install 1.15.2
  goup install go1.15.2
  goup install tip # Compile Go tip
  goup install tip 1234 # 1234 is the CL number

Flags:
  -h, --help          help for install
      --host string   host that is used to download Go. The GOUP_GO_HOST environment variable overrides this flag. (default "go.dev")

Global Flags:
  -v, --verbose   Verbose

FATA[0000] no binary release of go1.12 for darwin/arm64 at https://dl.google.com/go/go1.12.darwin-arm64.tar.gz

```
 goup install 1.21  
Error: no binary release of go1.21 for darwin/arm64 at https://dl.google.com/go/go1.21.darwin-arm64.tar.gz
Usage:
  goup install [VERSION] [flags]

Examples:

  goup install
  goup install 1.15.2
  goup install go1.15.2
  goup install tip # Compile Go tip
  goup install tip 1234 # 1234 is the CL number


Flags:
  -h, --help          help for install
      --host string   host that is used to download Go. The GOUP_GO_HOST environment variable overrides this flag. (default "go.dev")

Global Flags:
  -v, --verbose   Verbose

FATA[0000] no binary release of go1.21 for darwin/arm64 at https://dl.google.com/go/go1.21.darwin-arm64.tar.gz
```

**Comment by koron** [comment]
thank you for reporting this. i'll be looking into.

**Comment by koron** [comment]
This problem doesn't seem to be about this repository, but rather https://github.com/thinkgos/goup-rs
Please create a new issue for thinkgos/goup-rs

**Comment by koron** [comment]
Additional Information:

My goup shows this error when trying same thing.
It tries to install one from official releases.
And Go 1.12 offical release didn't include darwin/arm64.

Go 1.12's last release was released at Feb. 2020.
And first Apple M1 was released at Nov. 2020.
I remember that for a while after M1 was released, there was no Go running on M1.
It may be difficult to run Go 1.12 on drawin/arm64.

```console
$ goup install -goarch arm64 -goos darwin -root ./tmp/goroot 1.12
failed: no archives found for version=1.12 OS=darwin arch=arm64
```
